kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "frontend-builder"
spec:
  source:
    git:
      uri: "https://git-codecommit.eu-central-1.amazonaws.com/v1/repos/trackntrace-Frontend"
      ref: "BuildonOKD"
    sourceSecret:
      name: "aws"
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: "ImageStreamTag"
      name: "frontend:latest"