kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "frontend-builder"
spec:
  source:
    git:
      uri: "https://git-codecommit.eu-central-1.amazonaws.com/v1/repos/trackntrace-Frontend"
    sourceSecret:
      name: "aws"
    git:
      uri: "https://github.com/DerBrecher/sourcetofrontend.git"
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: "ImageStreamTag"
      name: "frontend"